language: go

go:
  - 1.7.x

sudo: required

services:
  - docker

script:
  - make
  - go test -cpu=1,2 -v -tags integration ./...

after_success:
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
    docker tag testgoserv testgoserv:$(cat VERSION);
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $DOCKER_USERNAME/testgoserv:$(cat VERSION);
    fi