version: '2'

services:

    balancer:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./nginx.conf/:/etc/nginx/
        depends_on:
            - app1
            - app2
        networks:
            - code-network

    app1:
        image: guzenok/testgoserv:latest
        environment:
            INSTANCE_NAME: App-Node-1
        networks:
            - code-network

    app2:
        image: guzenok/testgoserv:latest
        environment:
            INSTANCE_NAME: App-Node-2
        networks:
            - code-network

networks:
    code-network:
        driver: bridge